### ISSUE TITLE
Failed to create temp folder when not running armake as admin user in windows

### ISSUE THREAD

**Issue by nikolauska** [KoffeinFlummi/armake#16] opened 2016-08-27 14:21 UTC
### Operating system

Windows
### Description

When trying to build mission folders with python script on machine where user is not admin armake shows message:

```
error: failed to create temp folder
```
### Possible reason?

Currently armake uses `C:\Windows\Temp` as it's temp folder.  On windows every user has it's own temp folder inside AppData (`C:\Users\*username*\AppData\Local\Temp`) where programs save their temp files.

**Comment by netfusion** [comment] 2016-09-07 15:57
I may ran into the same issue.
While building a mission to create PBO file I got the same output:

> error: failed to create temp folder

I think the problem is that the mission does not contain a PBOPREFIX file. Armake then determines the temporary folder name from the source path.
Because of [this line](https://github.com/KoffeinFlummi/armake/blob/master/src/build.c#L248) the whole path is used on windows systems. If you use a explicit path it contains a ':' (e.g. `C:\Users\...`). This is a forbidden character for folder names.

Possible solution would be to to the path separator replacement earlier or change the linked lines to make them compatible with both OS.

Temporary solution is to use a relative source path without ':'.

**Comment by KoffeinFlummi** [comment] 2017-02-03 18:10
Fixed in b30a75b44bbd786f6707d4ef963c70a0343b6086

**Closed as completed by KoffeinFlummi** 2017-02-03 18:10 UTC
Labels: bug
